@url_dev=http://127.0.0.1:3055/v1/api

### SIGNUP
POST {{url_dev}}/shop/signup
content-type: application/json
x-api-key: secrectapikey

{
  "email": "vdhlong1202@gmail.com",
  "name": "Accel",
  "password": "abc123"
}

### LOGIN
POST {{url_dev}}/shop/login
content-type: application/json
x-api-key: secrectapikey

{
  "email": "vdhlong1202@gmail.com",
  "password": "abc123"
}

### LOGOUT
POST {{url_dev}}/shop/logout
content-type: application/json
x-api-key: secrectapikey
x-client-id: 64ca8bd32c151b425bad9932
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGNhOGJkMzJjMTUxYjQyNWJhZDk5MzIiLCJlbWFpbCI6InZkaGxvbmcxMjAyQGdtYWlsLmNvbSIsImlhdCI6MTY5MDk5NTcwNywiZXhwIjoxNjkxMTY4NTA3fQ.ZBwtIDwgy3OGqtfkDWen5Xr-2sOMRUidA2rNGPLCzBk6ezZ7ZVVgx-qMEm643fR1Snimxs72s2J4zX3LA-uA-QGYfLOE4H5qSRuaxV8zvCCGaUsQQYxOYjwSuIZ-eY8s7RYtMge0GzIFZxMGT8y2Pjh5qvkOB3_Vpkkptr9_WHuGmRcTUDh1kS7w5OPoT-kjTictHEucEs9q0baTXQaW8nMn6a-WHFJWAJmtI35DzoKjnXmoA7g9mz9QvQ_LAvcfsnYPyJmahAbKxXzyWUHbvgATyf1mYlXhFLzzG6wNhbSx9qgQMb5buYCJR-i3RNyPl17nvWN1a_pv8leqh1oq12gj2AliUEjLQXHLS9GGKeJNARy1290QHCJuvHRVloCCSCu8aPENfuMAAAC44cZbOMcvcizyas1aI82ZquMFBeTLfGDS6yBBqsFturrVO6TEHZgie3NFvcRQUBHHMy8bK8I-KzDp6J_BlSDOfPYwLCvCQibR-aHFOX8fTkBAZXpAg0-T0Z-d2tRaxH7lRMmcJc-vouae9aJRCPy16lG3fdq9gEsHbmaxIQScmB7yzi1PN8g2brMZRd931tRphZKzy3EhjNAN3DshnMxDRjLz1wRPEej2swQNYE36s_2kESLTP-lO6-QDBMMQoids59CEXWxfMzBlMmxryuah9l0xSCA


### REFRESH TOKEN
POST {{url_dev}}/shop/refresh
content-type: application/json
x-api-key: secrectapikey
x-client-id: 64ca8bd32c151b425bad9932
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGNhOGJkMzJjMTUxYjQyNWJhZDk5MzIiLCJlbWFpbCI6InZkaGxvbmcxMjAyQGdtYWlsLmNvbSIsImlhdCI6MTY5MDk5NTcwNywiZXhwIjoxNjkxMTY4NTA3fQ.ZBwtIDwgy3OGqtfkDWen5Xr-2sOMRUidA2rNGPLCzBk6ezZ7ZVVgx-qMEm643fR1Snimxs72s2J4zX3LA-uA-QGYfLOE4H5qSRuaxV8zvCCGaUsQQYxOYjwSuIZ-eY8s7RYtMge0GzIFZxMGT8y2Pjh5qvkOB3_Vpkkptr9_WHuGmRcTUDh1kS7w5OPoT-kjTictHEucEs9q0baTXQaW8nMn6a-WHFJWAJmtI35DzoKjnXmoA7g9mz9QvQ_LAvcfsnYPyJmahAbKxXzyWUHbvgATyf1mYlXhFLzzG6wNhbSx9qgQMb5buYCJR-i3RNyPl17nvWN1a_pv8leqh1oq12gj2AliUEjLQXHLS9GGKeJNARy1290QHCJuvHRVloCCSCu8aPENfuMAAAC44cZbOMcvcizyas1aI82ZquMFBeTLfGDS6yBBqsFturrVO6TEHZgie3NFvcRQUBHHMy8bK8I-KzDp6J_BlSDOfPYwLCvCQibR-aHFOX8fTkBAZXpAg0-T0Z-d2tRaxH7lRMmcJc-vouae9aJRCPy16lG3fdq9gEsHbmaxIQScmB7yzi1PN8g2brMZRd931tRphZKzy3EhjNAN3DshnMxDRjLz1wRPEej2swQNYE36s_2kESLTP-lO6-QDBMMQoids59CEXWxfMzBlMmxryuah9l0xSCA
x-rtoken-id: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGNhOGJkMzJjMTUxYjQyNWJhZDk5MzIiLCJlbWFpbCI6InZkaGxvbmcxMjAyQGdtYWlsLmNvbSIsImlhdCI6MTY5MTA2MDY3OSwiZXhwIjoxNjkxNjY1NDc5fQ.Yk_BTUujg16BLH7LnAz0etsHNO-PT3pVzsr6iWsIl9vb3B84sd7Ry5QubviRKpSwkaxC5ria9L1paNHwx1uVZPiY00oYDc8W3egyM59UdoYp64R_JImrtGM0nisz_VTmE8hP3ROxGI4zbG6PKJ8Tr_Az2fnS3sy2XY6kyIzf4lnH5gKkDf6Y8xWt7gEJJslYVBqLtZYcpMYPIprMvVXYcf3yd6eVZbW9c9U2h6uyV1dK6VSjF-1nUWgvnuL1lvp-xxl9geEr21GMSBOPBXATWQnvtYzs8RduLa0tgr-IIdMx-h94nzrgECCqziYBJJqf1SvCF5NHtpF-SyKsqmTHaG7DV5xQtE80CWvPQe8tO45NMhBNrD2WpelzO4y9UJ_x5cytT8GyntALmM73j9PyeU2TL_9toBZ-OvekpIBPEerlrbTFn0eFNleZls2QxzJEJcToLmaNt-7W24xyg0CxQOrZPiDOVUbnym38JyTNtCeA0TEK5A4cZ9DmyM2pWH3Hc_xphvyBIss3-evC_sywOxnDKsf_ScaNot8gMXSvaIkANJg6KAHDAXyj2xF3F5F1BPjaXMdbgOGIPRtv7oAi-u_kvYWSPYYCQQH3RUZe_-heHca5odzHuiO8yH-7Ux9C2kNcrSu9nRp7DR1_R5WIOnIYjS_R1zg5QLhHlDOdkBo

### CREATE PRODUCT
POST {{url_dev}}/product
content-type: application/json
x-api-key: secrectapikey
x-client-id: 64ca8bd32c151b425bad9932
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGNhOGJkMzJjMTUxYjQyNWJhZDk5MzIiLCJlbWFpbCI6InZkaGxvbmcxMjAyQGdtYWlsLmNvbSIsImlhdCI6MTY5MDk5NTcwNywiZXhwIjoxNjkxMTY4NTA3fQ.ZBwtIDwgy3OGqtfkDWen5Xr-2sOMRUidA2rNGPLCzBk6ezZ7ZVVgx-qMEm643fR1Snimxs72s2J4zX3LA-uA-QGYfLOE4H5qSRuaxV8zvCCGaUsQQYxOYjwSuIZ-eY8s7RYtMge0GzIFZxMGT8y2Pjh5qvkOB3_Vpkkptr9_WHuGmRcTUDh1kS7w5OPoT-kjTictHEucEs9q0baTXQaW8nMn6a-WHFJWAJmtI35DzoKjnXmoA7g9mz9QvQ_LAvcfsnYPyJmahAbKxXzyWUHbvgATyf1mYlXhFLzzG6wNhbSx9qgQMb5buYCJR-i3RNyPl17nvWN1a_pv8leqh1oq12gj2AliUEjLQXHLS9GGKeJNARy1290QHCJuvHRVloCCSCu8aPENfuMAAAC44cZbOMcvcizyas1aI82ZquMFBeTLfGDS6yBBqsFturrVO6TEHZgie3NFvcRQUBHHMy8bK8I-KzDp6J_BlSDOfPYwLCvCQibR-aHFOX8fTkBAZXpAg0-T0Z-d2tRaxH7lRMmcJc-vouae9aJRCPy16lG3fdq9gEsHbmaxIQScmB7yzi1PN8g2brMZRd931tRphZKzy3EhjNAN3DshnMxDRjLz1wRPEej2swQNYE36s_2kESLTP-lO6-QDBMMQoids59CEXWxfMzBlMmxryuah9l0xSCA
x-rtoken-id: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGNhOGJkMzJjMTUxYjQyNWJhZDk5MzIiLCJlbWFpbCI6InZkaGxvbmcxMjAyQGdtYWlsLmNvbSIsImlhdCI6MTY5NDM0NzkzNSwiZXhwIjoxNjk0OTUyNzM1fQ.CHRsjL5VWbc08CWT25pIf1C3E1ge3-UpABEkqORIoyy1eWz4ZnkFGwAb-mN979kKyFBwKuc3I-DxDJ7TCHYlMsJURkV5FDNKwdcSvc7dUcMHdE4Xia8dKwe2iPKx8AQzi2Do4jsv9g191wo2uCQBjBX5pKFNWSm-mjzofx2qrgfHFIp_D5_cpJb4RhKpyx5w0ZRb3MXLpsICGM-570OivKaq75fmkMpHL26_hzzUgAek0YAaSR2ThCZBTJcMFErbdnKwATD3oAOgPNJA3dtvM0pw7cYk0JoFCTz54kj6_7c5j5ZleTb0d4JQlXzLJjhJyUPn8SseyFjww2rZzby_t9pU9euDjvCPzg1DmHVxki9ZEnjoWVCBievnrF7lSFUoRvlcYkmUvghzWSdjfaRZhzJhOLnbep2i0nL7DbwY0Za3mrXUVHLINBqxnjMBTxcjLq-VDzEx-STc3ShNaHS7F_5-kU6b675cNtYPQ3Kr21qKLWMswPH44rw0SI7qaC4tFCj_VE3WPRwxeOxAFL8__argMN8JeFrsEwevQoseeVZB39bK8ddvLlp1xxqDw2TF9eFRrbi5zY0ecxjla9j0vrm4ScweBdJge1XJSmDgZek6UjAzf1rYOl75c5zUwDAM1uxpDff_4TjwR6Y9m8L0gSZSq1gDw4YWhBr7xBXdl94

{
  "product_name": "Red Shirt",
  "product_thumb": "https://www.youtube.com/watch?v=ZD5cWfsZO3A&t=74s",
  "product_description": "Uniqlo top flag branch, high quality",
  "product_price": 100,
  "product_quantity": 13,
  "product_type": "Clothing",
  "product_attributes": {
    "brand": "Uniqlo",
    "size": "M",
    "material": "100% cotton"
  }
}

### GET DRAFT PRODUCT
GET {{url_dev}}/product/draft/all
content-type: application/json
x-api-key: secrectapikey
x-client-id: 64ca8bd32c151b425bad9932
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGNhOGJkMzJjMTUxYjQyNWJhZDk5MzIiLCJlbWFpbCI6InZkaGxvbmcxMjAyQGdtYWlsLmNvbSIsImlhdCI6MTY5MDk5NTcwNywiZXhwIjoxNjkxMTY4NTA3fQ.ZBwtIDwgy3OGqtfkDWen5Xr-2sOMRUidA2rNGPLCzBk6ezZ7ZVVgx-qMEm643fR1Snimxs72s2J4zX3LA-uA-QGYfLOE4H5qSRuaxV8zvCCGaUsQQYxOYjwSuIZ-eY8s7RYtMge0GzIFZxMGT8y2Pjh5qvkOB3_Vpkkptr9_WHuGmRcTUDh1kS7w5OPoT-kjTictHEucEs9q0baTXQaW8nMn6a-WHFJWAJmtI35DzoKjnXmoA7g9mz9QvQ_LAvcfsnYPyJmahAbKxXzyWUHbvgATyf1mYlXhFLzzG6wNhbSx9qgQMb5buYCJR-i3RNyPl17nvWN1a_pv8leqh1oq12gj2AliUEjLQXHLS9GGKeJNARy1290QHCJuvHRVloCCSCu8aPENfuMAAAC44cZbOMcvcizyas1aI82ZquMFBeTLfGDS6yBBqsFturrVO6TEHZgie3NFvcRQUBHHMy8bK8I-KzDp6J_BlSDOfPYwLCvCQibR-aHFOX8fTkBAZXpAg0-T0Z-d2tRaxH7lRMmcJc-vouae9aJRCPy16lG3fdq9gEsHbmaxIQScmB7yzi1PN8g2brMZRd931tRphZKzy3EhjNAN3DshnMxDRjLz1wRPEej2swQNYE36s_2kESLTP-lO6-QDBMMQoids59CEXWxfMzBlMmxryuah9l0xSCA
x-rtoken-id: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGNhOGJkMzJjMTUxYjQyNWJhZDk5MzIiLCJlbWFpbCI6InZkaGxvbmcxMjAyQGdtYWlsLmNvbSIsImlhdCI6MTY5NDM0NzkzNSwiZXhwIjoxNjk0OTUyNzM1fQ.CHRsjL5VWbc08CWT25pIf1C3E1ge3-UpABEkqORIoyy1eWz4ZnkFGwAb-mN979kKyFBwKuc3I-DxDJ7TCHYlMsJURkV5FDNKwdcSvc7dUcMHdE4Xia8dKwe2iPKx8AQzi2Do4jsv9g191wo2uCQBjBX5pKFNWSm-mjzofx2qrgfHFIp_D5_cpJb4RhKpyx5w0ZRb3MXLpsICGM-570OivKaq75fmkMpHL26_hzzUgAek0YAaSR2ThCZBTJcMFErbdnKwATD3oAOgPNJA3dtvM0pw7cYk0JoFCTz54kj6_7c5j5ZleTb0d4JQlXzLJjhJyUPn8SseyFjww2rZzby_t9pU9euDjvCPzg1DmHVxki9ZEnjoWVCBievnrF7lSFUoRvlcYkmUvghzWSdjfaRZhzJhOLnbep2i0nL7DbwY0Za3mrXUVHLINBqxnjMBTxcjLq-VDzEx-STc3ShNaHS7F_5-kU6b675cNtYPQ3Kr21qKLWMswPH44rw0SI7qaC4tFCj_VE3WPRwxeOxAFL8__argMN8JeFrsEwevQoseeVZB39bK8ddvLlp1xxqDw2TF9eFRrbi5zY0ecxjla9j0vrm4ScweBdJge1XJSmDgZek6UjAzf1rYOl75c5zUwDAM1uxpDff_4TjwR6Y9m8L0gSZSq1gDw4YWhBr7xBXdl94


### GET PUBLISH PRODUCT
GET {{url_dev}}/product/publish/all
content-type: application/json
x-api-key: secrectapikey
x-client-id: 64ca8bd32c151b425bad9932
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGNhOGJkMzJjMTUxYjQyNWJhZDk5MzIiLCJlbWFpbCI6InZkaGxvbmcxMjAyQGdtYWlsLmNvbSIsImlhdCI6MTY5MDk5NTcwNywiZXhwIjoxNjkxMTY4NTA3fQ.ZBwtIDwgy3OGqtfkDWen5Xr-2sOMRUidA2rNGPLCzBk6ezZ7ZVVgx-qMEm643fR1Snimxs72s2J4zX3LA-uA-QGYfLOE4H5qSRuaxV8zvCCGaUsQQYxOYjwSuIZ-eY8s7RYtMge0GzIFZxMGT8y2Pjh5qvkOB3_Vpkkptr9_WHuGmRcTUDh1kS7w5OPoT-kjTictHEucEs9q0baTXQaW8nMn6a-WHFJWAJmtI35DzoKjnXmoA7g9mz9QvQ_LAvcfsnYPyJmahAbKxXzyWUHbvgATyf1mYlXhFLzzG6wNhbSx9qgQMb5buYCJR-i3RNyPl17nvWN1a_pv8leqh1oq12gj2AliUEjLQXHLS9GGKeJNARy1290QHCJuvHRVloCCSCu8aPENfuMAAAC44cZbOMcvcizyas1aI82ZquMFBeTLfGDS6yBBqsFturrVO6TEHZgie3NFvcRQUBHHMy8bK8I-KzDp6J_BlSDOfPYwLCvCQibR-aHFOX8fTkBAZXpAg0-T0Z-d2tRaxH7lRMmcJc-vouae9aJRCPy16lG3fdq9gEsHbmaxIQScmB7yzi1PN8g2brMZRd931tRphZKzy3EhjNAN3DshnMxDRjLz1wRPEej2swQNYE36s_2kESLTP-lO6-QDBMMQoids59CEXWxfMzBlMmxryuah9l0xSCA
x-rtoken-id: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGNhOGJkMzJjMTUxYjQyNWJhZDk5MzIiLCJlbWFpbCI6InZkaGxvbmcxMjAyQGdtYWlsLmNvbSIsImlhdCI6MTY5NDM0NzkzNSwiZXhwIjoxNjk0OTUyNzM1fQ.CHRsjL5VWbc08CWT25pIf1C3E1ge3-UpABEkqORIoyy1eWz4ZnkFGwAb-mN979kKyFBwKuc3I-DxDJ7TCHYlMsJURkV5FDNKwdcSvc7dUcMHdE4Xia8dKwe2iPKx8AQzi2Do4jsv9g191wo2uCQBjBX5pKFNWSm-mjzofx2qrgfHFIp_D5_cpJb4RhKpyx5w0ZRb3MXLpsICGM-570OivKaq75fmkMpHL26_hzzUgAek0YAaSR2ThCZBTJcMFErbdnKwATD3oAOgPNJA3dtvM0pw7cYk0JoFCTz54kj6_7c5j5ZleTb0d4JQlXzLJjhJyUPn8SseyFjww2rZzby_t9pU9euDjvCPzg1DmHVxki9ZEnjoWVCBievnrF7lSFUoRvlcYkmUvghzWSdjfaRZhzJhOLnbep2i0nL7DbwY0Za3mrXUVHLINBqxnjMBTxcjLq-VDzEx-STc3ShNaHS7F_5-kU6b675cNtYPQ3Kr21qKLWMswPH44rw0SI7qaC4tFCj_VE3WPRwxeOxAFL8__argMN8JeFrsEwevQoseeVZB39bK8ddvLlp1xxqDw2TF9eFRrbi5zY0ecxjla9j0vrm4ScweBdJge1XJSmDgZek6UjAzf1rYOl75c5zUwDAM1uxpDff_4TjwR6Y9m8L0gSZSq1gDw4YWhBr7xBXdl94

### SEARCH PRODUCT
GET {{url_dev}}/product/search/Shirt 
content-type: application/json

### GET ALL PRODUCT
GET {{url_dev}}/product
content-type: application/json

### GET PRODUCT DETAIL
GET {{url_dev}}/product/65008b4e09994bef47972dc8
content-type: application/json

### PUBLISH PRODUCT
POST {{url_dev}}/product/publish/64ff3eccd02f39200627c861
content-type: application/json
x-api-key: secrectapikey
x-client-id: 64ca8bd32c151b425bad9932
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGNhOGJkMzJjMTUxYjQyNWJhZDk5MzIiLCJlbWFpbCI6InZkaGxvbmcxMjAyQGdtYWlsLmNvbSIsImlhdCI6MTY5MDk5NTcwNywiZXhwIjoxNjkxMTY4NTA3fQ.ZBwtIDwgy3OGqtfkDWen5Xr-2sOMRUidA2rNGPLCzBk6ezZ7ZVVgx-qMEm643fR1Snimxs72s2J4zX3LA-uA-QGYfLOE4H5qSRuaxV8zvCCGaUsQQYxOYjwSuIZ-eY8s7RYtMge0GzIFZxMGT8y2Pjh5qvkOB3_Vpkkptr9_WHuGmRcTUDh1kS7w5OPoT-kjTictHEucEs9q0baTXQaW8nMn6a-WHFJWAJmtI35DzoKjnXmoA7g9mz9QvQ_LAvcfsnYPyJmahAbKxXzyWUHbvgATyf1mYlXhFLzzG6wNhbSx9qgQMb5buYCJR-i3RNyPl17nvWN1a_pv8leqh1oq12gj2AliUEjLQXHLS9GGKeJNARy1290QHCJuvHRVloCCSCu8aPENfuMAAAC44cZbOMcvcizyas1aI82ZquMFBeTLfGDS6yBBqsFturrVO6TEHZgie3NFvcRQUBHHMy8bK8I-KzDp6J_BlSDOfPYwLCvCQibR-aHFOX8fTkBAZXpAg0-T0Z-d2tRaxH7lRMmcJc-vouae9aJRCPy16lG3fdq9gEsHbmaxIQScmB7yzi1PN8g2brMZRd931tRphZKzy3EhjNAN3DshnMxDRjLz1wRPEej2swQNYE36s_2kESLTP-lO6-QDBMMQoids59CEXWxfMzBlMmxryuah9l0xSCA
x-rtoken-id: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGNhOGJkMzJjMTUxYjQyNWJhZDk5MzIiLCJlbWFpbCI6InZkaGxvbmcxMjAyQGdtYWlsLmNvbSIsImlhdCI6MTY5NDM0NzkzNSwiZXhwIjoxNjk0OTUyNzM1fQ.CHRsjL5VWbc08CWT25pIf1C3E1ge3-UpABEkqORIoyy1eWz4ZnkFGwAb-mN979kKyFBwKuc3I-DxDJ7TCHYlMsJURkV5FDNKwdcSvc7dUcMHdE4Xia8dKwe2iPKx8AQzi2Do4jsv9g191wo2uCQBjBX5pKFNWSm-mjzofx2qrgfHFIp_D5_cpJb4RhKpyx5w0ZRb3MXLpsICGM-570OivKaq75fmkMpHL26_hzzUgAek0YAaSR2ThCZBTJcMFErbdnKwATD3oAOgPNJA3dtvM0pw7cYk0JoFCTz54kj6_7c5j5ZleTb0d4JQlXzLJjhJyUPn8SseyFjww2rZzby_t9pU9euDjvCPzg1DmHVxki9ZEnjoWVCBievnrF7lSFUoRvlcYkmUvghzWSdjfaRZhzJhOLnbep2i0nL7DbwY0Za3mrXUVHLINBqxnjMBTxcjLq-VDzEx-STc3ShNaHS7F_5-kU6b675cNtYPQ3Kr21qKLWMswPH44rw0SI7qaC4tFCj_VE3WPRwxeOxAFL8__argMN8JeFrsEwevQoseeVZB39bK8ddvLlp1xxqDw2TF9eFRrbi5zY0ecxjla9j0vrm4ScweBdJge1XJSmDgZek6UjAzf1rYOl75c5zUwDAM1uxpDff_4TjwR6Y9m8L0gSZSq1gDw4YWhBr7xBXdl94

### UN PUBLISH PRODUCT
POST {{url_dev}}/product/unpublish/64ff3eccd02f39200627c861
content-type: application/json
x-api-key: secrectapikey
x-client-id: 64ca8bd32c151b425bad9932
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGNhOGJkMzJjMTUxYjQyNWJhZDk5MzIiLCJlbWFpbCI6InZkaGxvbmcxMjAyQGdtYWlsLmNvbSIsImlhdCI6MTY5MDk5NTcwNywiZXhwIjoxNjkxMTY4NTA3fQ.ZBwtIDwgy3OGqtfkDWen5Xr-2sOMRUidA2rNGPLCzBk6ezZ7ZVVgx-qMEm643fR1Snimxs72s2J4zX3LA-uA-QGYfLOE4H5qSRuaxV8zvCCGaUsQQYxOYjwSuIZ-eY8s7RYtMge0GzIFZxMGT8y2Pjh5qvkOB3_Vpkkptr9_WHuGmRcTUDh1kS7w5OPoT-kjTictHEucEs9q0baTXQaW8nMn6a-WHFJWAJmtI35DzoKjnXmoA7g9mz9QvQ_LAvcfsnYPyJmahAbKxXzyWUHbvgATyf1mYlXhFLzzG6wNhbSx9qgQMb5buYCJR-i3RNyPl17nvWN1a_pv8leqh1oq12gj2AliUEjLQXHLS9GGKeJNARy1290QHCJuvHRVloCCSCu8aPENfuMAAAC44cZbOMcvcizyas1aI82ZquMFBeTLfGDS6yBBqsFturrVO6TEHZgie3NFvcRQUBHHMy8bK8I-KzDp6J_BlSDOfPYwLCvCQibR-aHFOX8fTkBAZXpAg0-T0Z-d2tRaxH7lRMmcJc-vouae9aJRCPy16lG3fdq9gEsHbmaxIQScmB7yzi1PN8g2brMZRd931tRphZKzy3EhjNAN3DshnMxDRjLz1wRPEej2swQNYE36s_2kESLTP-lO6-QDBMMQoids59CEXWxfMzBlMmxryuah9l0xSCA
x-rtoken-id: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGNhOGJkMzJjMTUxYjQyNWJhZDk5MzIiLCJlbWFpbCI6InZkaGxvbmcxMjAyQGdtYWlsLmNvbSIsImlhdCI6MTY5NDM0NzkzNSwiZXhwIjoxNjk0OTUyNzM1fQ.CHRsjL5VWbc08CWT25pIf1C3E1ge3-UpABEkqORIoyy1eWz4ZnkFGwAb-mN979kKyFBwKuc3I-DxDJ7TCHYlMsJURkV5FDNKwdcSvc7dUcMHdE4Xia8dKwe2iPKx8AQzi2Do4jsv9g191wo2uCQBjBX5pKFNWSm-mjzofx2qrgfHFIp_D5_cpJb4RhKpyx5w0ZRb3MXLpsICGM-570OivKaq75fmkMpHL26_hzzUgAek0YAaSR2ThCZBTJcMFErbdnKwATD3oAOgPNJA3dtvM0pw7cYk0JoFCTz54kj6_7c5j5ZleTb0d4JQlXzLJjhJyUPn8SseyFjww2rZzby_t9pU9euDjvCPzg1DmHVxki9ZEnjoWVCBievnrF7lSFUoRvlcYkmUvghzWSdjfaRZhzJhOLnbep2i0nL7DbwY0Za3mrXUVHLINBqxnjMBTxcjLq-VDzEx-STc3ShNaHS7F_5-kU6b675cNtYPQ3Kr21qKLWMswPH44rw0SI7qaC4tFCj_VE3WPRwxeOxAFL8__argMN8JeFrsEwevQoseeVZB39bK8ddvLlp1xxqDw2TF9eFRrbi5zY0ecxjla9j0vrm4ScweBdJge1XJSmDgZek6UjAzf1rYOl75c5zUwDAM1uxpDff_4TjwR6Y9m8L0gSZSq1gDw4YWhBr7xBXdl94