@url_dev=http://127.0.0.1:3055/v1/api

### SIGNUP
POST {{url_dev}}/shop/signup
content-type: application/json
x-api-key: secrectapikey

{
  "email": "test@gmail.com",
  "name": "Accel Test",
  "password": "abc123"
}

### LOGIN
POST {{url_dev}}/shop/login
content-type: application/json
x-api-key: secrectapikey

{
  "email": "vdhlong1202@gmail.com",
  "password": "abc123"
}

### LOGOUT
POST {{url_dev}}/shop/logout
content-type: application/json
x-api-key: secrectapikey
x-client-id: 64ca8bd32c151b425bad9932
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGNhOGJkMzJjMTUxYjQyNWJhZDk5MzIiLCJlbWFpbCI6InZkaGxvbmcxMjAyQGdtYWlsLmNvbSIsImlhdCI6MTY5MDk5NTcwNywiZXhwIjoxNjkxMTY4NTA3fQ.ZBwtIDwgy3OGqtfkDWen5Xr-2sOMRUidA2rNGPLCzBk6ezZ7ZVVgx-qMEm643fR1Snimxs72s2J4zX3LA-uA-QGYfLOE4H5qSRuaxV8zvCCGaUsQQYxOYjwSuIZ-eY8s7RYtMge0GzIFZxMGT8y2Pjh5qvkOB3_Vpkkptr9_WHuGmRcTUDh1kS7w5OPoT-kjTictHEucEs9q0baTXQaW8nMn6a-WHFJWAJmtI35DzoKjnXmoA7g9mz9QvQ_LAvcfsnYPyJmahAbKxXzyWUHbvgATyf1mYlXhFLzzG6wNhbSx9qgQMb5buYCJR-i3RNyPl17nvWN1a_pv8leqh1oq12gj2AliUEjLQXHLS9GGKeJNARy1290QHCJuvHRVloCCSCu8aPENfuMAAAC44cZbOMcvcizyas1aI82ZquMFBeTLfGDS6yBBqsFturrVO6TEHZgie3NFvcRQUBHHMy8bK8I-KzDp6J_BlSDOfPYwLCvCQibR-aHFOX8fTkBAZXpAg0-T0Z-d2tRaxH7lRMmcJc-vouae9aJRCPy16lG3fdq9gEsHbmaxIQScmB7yzi1PN8g2brMZRd931tRphZKzy3EhjNAN3DshnMxDRjLz1wRPEej2swQNYE36s_2kESLTP-lO6-QDBMMQoids59CEXWxfMzBlMmxryuah9l0xSCA


### REFRESH TOKEN
POST {{url_dev}}/shop/refresh
content-type: application/json
x-api-key: secrectapikey
x-client-id: 64ca8bd32c151b425bad9932
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGNhOGJkMzJjMTUxYjQyNWJhZDk5MzIiLCJlbWFpbCI6InZkaGxvbmcxMjAyQGdtYWlsLmNvbSIsImlhdCI6MTY5MDk5NTcwNywiZXhwIjoxNjkxMTY4NTA3fQ.ZBwtIDwgy3OGqtfkDWen5Xr-2sOMRUidA2rNGPLCzBk6ezZ7ZVVgx-qMEm643fR1Snimxs72s2J4zX3LA-uA-QGYfLOE4H5qSRuaxV8zvCCGaUsQQYxOYjwSuIZ-eY8s7RYtMge0GzIFZxMGT8y2Pjh5qvkOB3_Vpkkptr9_WHuGmRcTUDh1kS7w5OPoT-kjTictHEucEs9q0baTXQaW8nMn6a-WHFJWAJmtI35DzoKjnXmoA7g9mz9QvQ_LAvcfsnYPyJmahAbKxXzyWUHbvgATyf1mYlXhFLzzG6wNhbSx9qgQMb5buYCJR-i3RNyPl17nvWN1a_pv8leqh1oq12gj2AliUEjLQXHLS9GGKeJNARy1290QHCJuvHRVloCCSCu8aPENfuMAAAC44cZbOMcvcizyas1aI82ZquMFBeTLfGDS6yBBqsFturrVO6TEHZgie3NFvcRQUBHHMy8bK8I-KzDp6J_BlSDOfPYwLCvCQibR-aHFOX8fTkBAZXpAg0-T0Z-d2tRaxH7lRMmcJc-vouae9aJRCPy16lG3fdq9gEsHbmaxIQScmB7yzi1PN8g2brMZRd931tRphZKzy3EhjNAN3DshnMxDRjLz1wRPEej2swQNYE36s_2kESLTP-lO6-QDBMMQoids59CEXWxfMzBlMmxryuah9l0xSCA
x-rtoken-id: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGNhOGJkMzJjMTUxYjQyNWJhZDk5MzIiLCJlbWFpbCI6InZkaGxvbmcxMjAyQGdtYWlsLmNvbSIsImlhdCI6MTY5MTA2MDY3OSwiZXhwIjoxNjkxNjY1NDc5fQ.Yk_BTUujg16BLH7LnAz0etsHNO-PT3pVzsr6iWsIl9vb3B84sd7Ry5QubviRKpSwkaxC5ria9L1paNHwx1uVZPiY00oYDc8W3egyM59UdoYp64R_JImrtGM0nisz_VTmE8hP3ROxGI4zbG6PKJ8Tr_Az2fnS3sy2XY6kyIzf4lnH5gKkDf6Y8xWt7gEJJslYVBqLtZYcpMYPIprMvVXYcf3yd6eVZbW9c9U2h6uyV1dK6VSjF-1nUWgvnuL1lvp-xxl9geEr21GMSBOPBXATWQnvtYzs8RduLa0tgr-IIdMx-h94nzrgECCqziYBJJqf1SvCF5NHtpF-SyKsqmTHaG7DV5xQtE80CWvPQe8tO45NMhBNrD2WpelzO4y9UJ_x5cytT8GyntALmM73j9PyeU2TL_9toBZ-OvekpIBPEerlrbTFn0eFNleZls2QxzJEJcToLmaNt-7W24xyg0CxQOrZPiDOVUbnym38JyTNtCeA0TEK5A4cZ9DmyM2pWH3Hc_xphvyBIss3-evC_sywOxnDKsf_ScaNot8gMXSvaIkANJg6KAHDAXyj2xF3F5F1BPjaXMdbgOGIPRtv7oAi-u_kvYWSPYYCQQH3RUZe_-heHca5odzHuiO8yH-7Ux9C2kNcrSu9nRp7DR1_R5WIOnIYjS_R1zg5QLhHlDOdkBo

### CREATE PRODUCT
POST {{url_dev}}/product
content-type: application/json
x-api-key: secrectapikey
x-client-id: 65411d6abe7a79029ecadbd4
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTQxMWQ2YWJlN2E3OTAyOWVjYWRiZDQiLCJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwiaWF0IjoxNjk4NzY2MTg5LCJleHAiOjE2OTg5Mzg5ODl9.SaAPVFYrJieZnPJjzmjSkrvplJCtbGCXDCg2Z_yf_lJPJ5KWZ1F2NSyld9z74ifGDi36WUulp0dNuniidg4cUKyaZ16c7wGYYGl0OEfk8B84hWD8JCLI7wHMtm8pcBkMtjXt49Iq82XBFJmzFxWkrxMi27cljpU9F1bFEoLoXJr56zFVc2ixHEVPazROzSSCWNKc4QHD3vndHltY3Sqz_aQt9kE9ZHCA7atlDERgOnAH9qTzXIuqff9IduvxNhqhkDLTrt9Tuf-rKYyjYoioFqYt1yGFIvQ1AKBLYsprLP9qOzfHiHWa0vzdHlaSixFJQr1rzgn3T_RQu4QWfnh6I0FMbuFI5IV1K1QBF8ncLrPFjuS1EPQtH1lWeVNsFTQ5AMnms8TNa-LJZ_4KMqkum7r9JOz1I4bj8lVcFvDi1d38T-7NDnk9GTbsqVU4zb6zZFMI5_PCz2TgNERhgqoe4shoq-E5-qMSug5If-tlLTBAKBRlj4RBKPA-sqBwW7APXwSbQmngz8I7hDdB2scCWJoAx-YT9MeHri33VCeQVavWZiLLM7wlx-uE0oJnr4JapYnfcB5E3Uct7sCR_VRAi_nVRvcfi0pKXG3knXu0yrfKkHfSBAc77rrTb8UuhDg4aeXTFrRZhBGP-0bvdMJq1fW89vocec7JK0KyfeH1Bag
x-rtoken-id: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTQxMWQ2YWJlN2E3OTAyOWVjYWRiZDQiLCJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwiaWF0IjoxNjk4NzY2MTg5LCJleHAiOjE2OTkzNzA5ODl9.F7jA2pjWy_k_P-qyaVeVgB6yVw5K1UjBxdqEUVte9YOeWFkfh28sdagPoO9Sj4SLXU3cKNBtUF3hdoo5YTwjMvTVLPf9MP3gMyw599U5yV3kuzLw73V8WMPsXsn-KQ5AIFEYOA5sn5uxasvJnm9zg-8Y-NT_m3hrPuq4UBiELZwszpe1TJai-4KztIFNxeRP2YmY33Li6HHp0kcjVK0CtUH0tD92HWqHhFzC7B_qCoCZRXe76Ws_UUBrjUGBpUBWnXY26b_BIExMLDrEW8fyiJyCFok8eDHUwUeG_1oBV5IZH1On6kx5mhaiV6ueli284JHn_f36kppnIJ0YV1Ezytlf38dDA6irfv_H87aw624Bj3yzQRkmp-zufHh66zki9X9fDeVfZjNISGjn828WN8sESYWAVOTVIntT0p_gYsmMNEgcXf8NsUK22KjKS89sRVniXy-BdTa-N5Wtr88FllJGWVqlcY97vdZ_vEb12RSpK1tAQNN-qQkS1Kzkjlf4QCtJToenrCBCZMtGtWPyTtiitVzSn2p-LN2wr9CMKs9tqSty7bVFhNPsRiyvoFQg5Oj7OYN8A0v_KtONeHS4n1VTldBR7RYUGJ6vVeY9VtJDf8KAmfMv-T33SfeyX5bl2kAP3FFnwCLvwIFGV9xcofEh_QaL53h2OZzy_khlHtQ

{
  "product_name": "Magic Lattern",
  "product_thumb": "https://www.youtube.com/watch?v=ZD5cWfsZO3A&t=74s",
  "product_description": "Uniqlo top flag branch, high quality",
  "product_price": 500,
  "product_quantity": 22,
  "product_type": "Clothing",
  "product_attributes": {
    "brand": "Uniqlo",
    "size": "S",
    "material": "150% cotton 2"
  }
}

### GET DRAFT PRODUCT
GET {{url_dev}}/product/draft/all
content-type: application/json
x-api-key: secrectapikey
x-client-id: 64ca8bd32c151b425bad9932
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGNhOGJkMzJjMTUxYjQyNWJhZDk5MzIiLCJlbWFpbCI6InZkaGxvbmcxMjAyQGdtYWlsLmNvbSIsImlhdCI6MTY5MDk5NTcwNywiZXhwIjoxNjkxMTY4NTA3fQ.ZBwtIDwgy3OGqtfkDWen5Xr-2sOMRUidA2rNGPLCzBk6ezZ7ZVVgx-qMEm643fR1Snimxs72s2J4zX3LA-uA-QGYfLOE4H5qSRuaxV8zvCCGaUsQQYxOYjwSuIZ-eY8s7RYtMge0GzIFZxMGT8y2Pjh5qvkOB3_Vpkkptr9_WHuGmRcTUDh1kS7w5OPoT-kjTictHEucEs9q0baTXQaW8nMn6a-WHFJWAJmtI35DzoKjnXmoA7g9mz9QvQ_LAvcfsnYPyJmahAbKxXzyWUHbvgATyf1mYlXhFLzzG6wNhbSx9qgQMb5buYCJR-i3RNyPl17nvWN1a_pv8leqh1oq12gj2AliUEjLQXHLS9GGKeJNARy1290QHCJuvHRVloCCSCu8aPENfuMAAAC44cZbOMcvcizyas1aI82ZquMFBeTLfGDS6yBBqsFturrVO6TEHZgie3NFvcRQUBHHMy8bK8I-KzDp6J_BlSDOfPYwLCvCQibR-aHFOX8fTkBAZXpAg0-T0Z-d2tRaxH7lRMmcJc-vouae9aJRCPy16lG3fdq9gEsHbmaxIQScmB7yzi1PN8g2brMZRd931tRphZKzy3EhjNAN3DshnMxDRjLz1wRPEej2swQNYE36s_2kESLTP-lO6-QDBMMQoids59CEXWxfMzBlMmxryuah9l0xSCA
x-rtoken-id: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGNhOGJkMzJjMTUxYjQyNWJhZDk5MzIiLCJlbWFpbCI6InZkaGxvbmcxMjAyQGdtYWlsLmNvbSIsImlhdCI6MTY5NDM0NzkzNSwiZXhwIjoxNjk0OTUyNzM1fQ.CHRsjL5VWbc08CWT25pIf1C3E1ge3-UpABEkqORIoyy1eWz4ZnkFGwAb-mN979kKyFBwKuc3I-DxDJ7TCHYlMsJURkV5FDNKwdcSvc7dUcMHdE4Xia8dKwe2iPKx8AQzi2Do4jsv9g191wo2uCQBjBX5pKFNWSm-mjzofx2qrgfHFIp_D5_cpJb4RhKpyx5w0ZRb3MXLpsICGM-570OivKaq75fmkMpHL26_hzzUgAek0YAaSR2ThCZBTJcMFErbdnKwATD3oAOgPNJA3dtvM0pw7cYk0JoFCTz54kj6_7c5j5ZleTb0d4JQlXzLJjhJyUPn8SseyFjww2rZzby_t9pU9euDjvCPzg1DmHVxki9ZEnjoWVCBievnrF7lSFUoRvlcYkmUvghzWSdjfaRZhzJhOLnbep2i0nL7DbwY0Za3mrXUVHLINBqxnjMBTxcjLq-VDzEx-STc3ShNaHS7F_5-kU6b675cNtYPQ3Kr21qKLWMswPH44rw0SI7qaC4tFCj_VE3WPRwxeOxAFL8__argMN8JeFrsEwevQoseeVZB39bK8ddvLlp1xxqDw2TF9eFRrbi5zY0ecxjla9j0vrm4ScweBdJge1XJSmDgZek6UjAzf1rYOl75c5zUwDAM1uxpDff_4TjwR6Y9m8L0gSZSq1gDw4YWhBr7xBXdl94


### GET PUBLISH PRODUCT
GET {{url_dev}}/product/publish/all
content-type: application/json
x-api-key: secrectapikey
x-client-id: 64ca8bd32c151b425bad9932
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGNhOGJkMzJjMTUxYjQyNWJhZDk5MzIiLCJlbWFpbCI6InZkaGxvbmcxMjAyQGdtYWlsLmNvbSIsImlhdCI6MTY5MDk5NTcwNywiZXhwIjoxNjkxMTY4NTA3fQ.ZBwtIDwgy3OGqtfkDWen5Xr-2sOMRUidA2rNGPLCzBk6ezZ7ZVVgx-qMEm643fR1Snimxs72s2J4zX3LA-uA-QGYfLOE4H5qSRuaxV8zvCCGaUsQQYxOYjwSuIZ-eY8s7RYtMge0GzIFZxMGT8y2Pjh5qvkOB3_Vpkkptr9_WHuGmRcTUDh1kS7w5OPoT-kjTictHEucEs9q0baTXQaW8nMn6a-WHFJWAJmtI35DzoKjnXmoA7g9mz9QvQ_LAvcfsnYPyJmahAbKxXzyWUHbvgATyf1mYlXhFLzzG6wNhbSx9qgQMb5buYCJR-i3RNyPl17nvWN1a_pv8leqh1oq12gj2AliUEjLQXHLS9GGKeJNARy1290QHCJuvHRVloCCSCu8aPENfuMAAAC44cZbOMcvcizyas1aI82ZquMFBeTLfGDS6yBBqsFturrVO6TEHZgie3NFvcRQUBHHMy8bK8I-KzDp6J_BlSDOfPYwLCvCQibR-aHFOX8fTkBAZXpAg0-T0Z-d2tRaxH7lRMmcJc-vouae9aJRCPy16lG3fdq9gEsHbmaxIQScmB7yzi1PN8g2brMZRd931tRphZKzy3EhjNAN3DshnMxDRjLz1wRPEej2swQNYE36s_2kESLTP-lO6-QDBMMQoids59CEXWxfMzBlMmxryuah9l0xSCA
x-rtoken-id: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGNhOGJkMzJjMTUxYjQyNWJhZDk5MzIiLCJlbWFpbCI6InZkaGxvbmcxMjAyQGdtYWlsLmNvbSIsImlhdCI6MTY5NDM0NzkzNSwiZXhwIjoxNjk0OTUyNzM1fQ.CHRsjL5VWbc08CWT25pIf1C3E1ge3-UpABEkqORIoyy1eWz4ZnkFGwAb-mN979kKyFBwKuc3I-DxDJ7TCHYlMsJURkV5FDNKwdcSvc7dUcMHdE4Xia8dKwe2iPKx8AQzi2Do4jsv9g191wo2uCQBjBX5pKFNWSm-mjzofx2qrgfHFIp_D5_cpJb4RhKpyx5w0ZRb3MXLpsICGM-570OivKaq75fmkMpHL26_hzzUgAek0YAaSR2ThCZBTJcMFErbdnKwATD3oAOgPNJA3dtvM0pw7cYk0JoFCTz54kj6_7c5j5ZleTb0d4JQlXzLJjhJyUPn8SseyFjww2rZzby_t9pU9euDjvCPzg1DmHVxki9ZEnjoWVCBievnrF7lSFUoRvlcYkmUvghzWSdjfaRZhzJhOLnbep2i0nL7DbwY0Za3mrXUVHLINBqxnjMBTxcjLq-VDzEx-STc3ShNaHS7F_5-kU6b675cNtYPQ3Kr21qKLWMswPH44rw0SI7qaC4tFCj_VE3WPRwxeOxAFL8__argMN8JeFrsEwevQoseeVZB39bK8ddvLlp1xxqDw2TF9eFRrbi5zY0ecxjla9j0vrm4ScweBdJge1XJSmDgZek6UjAzf1rYOl75c5zUwDAM1uxpDff_4TjwR6Y9m8L0gSZSq1gDw4YWhBr7xBXdl94

### SEARCH PRODUCT
GET {{url_dev}}/product/search/Shirt 
content-type: application/json

### GET ALL PRODUCT
GET {{url_dev}}/product
content-type: application/json

### GET PRODUCT DETAIL
GET {{url_dev}}/product/64ff3eccd02f39200627c861
content-type: application/json

### PUBLISH PRODUCT
POST {{url_dev}}/product/publish/65411ecf22126e08b4cd9f51
content-type: application/json
x-api-key: secrectapikey
x-client-id: 65411d6abe7a79029ecadbd4
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTQxMWQ2YWJlN2E3OTAyOWVjYWRiZDQiLCJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwiaWF0IjoxNjk4NzY2MTg5LCJleHAiOjE2OTg5Mzg5ODl9.SaAPVFYrJieZnPJjzmjSkrvplJCtbGCXDCg2Z_yf_lJPJ5KWZ1F2NSyld9z74ifGDi36WUulp0dNuniidg4cUKyaZ16c7wGYYGl0OEfk8B84hWD8JCLI7wHMtm8pcBkMtjXt49Iq82XBFJmzFxWkrxMi27cljpU9F1bFEoLoXJr56zFVc2ixHEVPazROzSSCWNKc4QHD3vndHltY3Sqz_aQt9kE9ZHCA7atlDERgOnAH9qTzXIuqff9IduvxNhqhkDLTrt9Tuf-rKYyjYoioFqYt1yGFIvQ1AKBLYsprLP9qOzfHiHWa0vzdHlaSixFJQr1rzgn3T_RQu4QWfnh6I0FMbuFI5IV1K1QBF8ncLrPFjuS1EPQtH1lWeVNsFTQ5AMnms8TNa-LJZ_4KMqkum7r9JOz1I4bj8lVcFvDi1d38T-7NDnk9GTbsqVU4zb6zZFMI5_PCz2TgNERhgqoe4shoq-E5-qMSug5If-tlLTBAKBRlj4RBKPA-sqBwW7APXwSbQmngz8I7hDdB2scCWJoAx-YT9MeHri33VCeQVavWZiLLM7wlx-uE0oJnr4JapYnfcB5E3Uct7sCR_VRAi_nVRvcfi0pKXG3knXu0yrfKkHfSBAc77rrTb8UuhDg4aeXTFrRZhBGP-0bvdMJq1fW89vocec7JK0KyfeH1Bag
x-rtoken-id: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTQxMWQ2YWJlN2E3OTAyOWVjYWRiZDQiLCJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwiaWF0IjoxNjk4NzY2MTg5LCJleHAiOjE2OTkzNzA5ODl9.F7jA2pjWy_k_P-qyaVeVgB6yVw5K1UjBxdqEUVte9YOeWFkfh28sdagPoO9Sj4SLXU3cKNBtUF3hdoo5YTwjMvTVLPf9MP3gMyw599U5yV3kuzLw73V8WMPsXsn-KQ5AIFEYOA5sn5uxasvJnm9zg-8Y-NT_m3hrPuq4UBiELZwszpe1TJai-4KztIFNxeRP2YmY33Li6HHp0kcjVK0CtUH0tD92HWqHhFzC7B_qCoCZRXe76Ws_UUBrjUGBpUBWnXY26b_BIExMLDrEW8fyiJyCFok8eDHUwUeG_1oBV5IZH1On6kx5mhaiV6ueli284JHn_f36kppnIJ0YV1Ezytlf38dDA6irfv_H87aw624Bj3yzQRkmp-zufHh66zki9X9fDeVfZjNISGjn828WN8sESYWAVOTVIntT0p_gYsmMNEgcXf8NsUK22KjKS89sRVniXy-BdTa-N5Wtr88FllJGWVqlcY97vdZ_vEb12RSpK1tAQNN-qQkS1Kzkjlf4QCtJToenrCBCZMtGtWPyTtiitVzSn2p-LN2wr9CMKs9tqSty7bVFhNPsRiyvoFQg5Oj7OYN8A0v_KtONeHS4n1VTldBR7RYUGJ6vVeY9VtJDf8KAmfMv-T33SfeyX5bl2kAP3FFnwCLvwIFGV9xcofEh_QaL53h2OZzy_khlHtQ

### UN PUBLISH PRODUCT
POST {{url_dev}}/product/unpublish/64ff3eccd02f39200627c861
content-type: application/json
x-api-key: secrectapikey
x-client-id: 64ca8bd32c151b425bad9932
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGNhOGJkMzJjMTUxYjQyNWJhZDk5MzIiLCJlbWFpbCI6InZkaGxvbmcxMjAyQGdtYWlsLmNvbSIsImlhdCI6MTY5MDk5NTcwNywiZXhwIjoxNjkxMTY4NTA3fQ.ZBwtIDwgy3OGqtfkDWen5Xr-2sOMRUidA2rNGPLCzBk6ezZ7ZVVgx-qMEm643fR1Snimxs72s2J4zX3LA-uA-QGYfLOE4H5qSRuaxV8zvCCGaUsQQYxOYjwSuIZ-eY8s7RYtMge0GzIFZxMGT8y2Pjh5qvkOB3_Vpkkptr9_WHuGmRcTUDh1kS7w5OPoT-kjTictHEucEs9q0baTXQaW8nMn6a-WHFJWAJmtI35DzoKjnXmoA7g9mz9QvQ_LAvcfsnYPyJmahAbKxXzyWUHbvgATyf1mYlXhFLzzG6wNhbSx9qgQMb5buYCJR-i3RNyPl17nvWN1a_pv8leqh1oq12gj2AliUEjLQXHLS9GGKeJNARy1290QHCJuvHRVloCCSCu8aPENfuMAAAC44cZbOMcvcizyas1aI82ZquMFBeTLfGDS6yBBqsFturrVO6TEHZgie3NFvcRQUBHHMy8bK8I-KzDp6J_BlSDOfPYwLCvCQibR-aHFOX8fTkBAZXpAg0-T0Z-d2tRaxH7lRMmcJc-vouae9aJRCPy16lG3fdq9gEsHbmaxIQScmB7yzi1PN8g2brMZRd931tRphZKzy3EhjNAN3DshnMxDRjLz1wRPEej2swQNYE36s_2kESLTP-lO6-QDBMMQoids59CEXWxfMzBlMmxryuah9l0xSCA
x-rtoken-id: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGNhOGJkMzJjMTUxYjQyNWJhZDk5MzIiLCJlbWFpbCI6InZkaGxvbmcxMjAyQGdtYWlsLmNvbSIsImlhdCI6MTY5NDM0NzkzNSwiZXhwIjoxNjk0OTUyNzM1fQ.CHRsjL5VWbc08CWT25pIf1C3E1ge3-UpABEkqORIoyy1eWz4ZnkFGwAb-mN979kKyFBwKuc3I-DxDJ7TCHYlMsJURkV5FDNKwdcSvc7dUcMHdE4Xia8dKwe2iPKx8AQzi2Do4jsv9g191wo2uCQBjBX5pKFNWSm-mjzofx2qrgfHFIp_D5_cpJb4RhKpyx5w0ZRb3MXLpsICGM-570OivKaq75fmkMpHL26_hzzUgAek0YAaSR2ThCZBTJcMFErbdnKwATD3oAOgPNJA3dtvM0pw7cYk0JoFCTz54kj6_7c5j5ZleTb0d4JQlXzLJjhJyUPn8SseyFjww2rZzby_t9pU9euDjvCPzg1DmHVxki9ZEnjoWVCBievnrF7lSFUoRvlcYkmUvghzWSdjfaRZhzJhOLnbep2i0nL7DbwY0Za3mrXUVHLINBqxnjMBTxcjLq-VDzEx-STc3ShNaHS7F_5-kU6b675cNtYPQ3Kr21qKLWMswPH44rw0SI7qaC4tFCj_VE3WPRwxeOxAFL8__argMN8JeFrsEwevQoseeVZB39bK8ddvLlp1xxqDw2TF9eFRrbi5zY0ecxjla9j0vrm4ScweBdJge1XJSmDgZek6UjAzf1rYOl75c5zUwDAM1uxpDff_4TjwR6Y9m8L0gSZSq1gDw4YWhBr7xBXdl94


### UPDATE PRODUCT
PATCH {{url_dev}}/product/64ff3eccd02f39200627c861
content-type: application/json
x-api-key: secrectapikey
x-client-id: 64ca8bd32c151b425bad9932
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGNhOGJkMzJjMTUxYjQyNWJhZDk5MzIiLCJlbWFpbCI6InZkaGxvbmcxMjAyQGdtYWlsLmNvbSIsImlhdCI6MTY5MDk5NTcwNywiZXhwIjoxNjkxMTY4NTA3fQ.ZBwtIDwgy3OGqtfkDWen5Xr-2sOMRUidA2rNGPLCzBk6ezZ7ZVVgx-qMEm643fR1Snimxs72s2J4zX3LA-uA-QGYfLOE4H5qSRuaxV8zvCCGaUsQQYxOYjwSuIZ-eY8s7RYtMge0GzIFZxMGT8y2Pjh5qvkOB3_Vpkkptr9_WHuGmRcTUDh1kS7w5OPoT-kjTictHEucEs9q0baTXQaW8nMn6a-WHFJWAJmtI35DzoKjnXmoA7g9mz9QvQ_LAvcfsnYPyJmahAbKxXzyWUHbvgATyf1mYlXhFLzzG6wNhbSx9qgQMb5buYCJR-i3RNyPl17nvWN1a_pv8leqh1oq12gj2AliUEjLQXHLS9GGKeJNARy1290QHCJuvHRVloCCSCu8aPENfuMAAAC44cZbOMcvcizyas1aI82ZquMFBeTLfGDS6yBBqsFturrVO6TEHZgie3NFvcRQUBHHMy8bK8I-KzDp6J_BlSDOfPYwLCvCQibR-aHFOX8fTkBAZXpAg0-T0Z-d2tRaxH7lRMmcJc-vouae9aJRCPy16lG3fdq9gEsHbmaxIQScmB7yzi1PN8g2brMZRd931tRphZKzy3EhjNAN3DshnMxDRjLz1wRPEej2swQNYE36s_2kESLTP-lO6-QDBMMQoids59CEXWxfMzBlMmxryuah9l0xSCA
x-rtoken-id: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGNhOGJkMzJjMTUxYjQyNWJhZDk5MzIiLCJlbWFpbCI6InZkaGxvbmcxMjAyQGdtYWlsLmNvbSIsImlhdCI6MTY5NDM0NzkzNSwiZXhwIjoxNjk0OTUyNzM1fQ.CHRsjL5VWbc08CWT25pIf1C3E1ge3-UpABEkqORIoyy1eWz4ZnkFGwAb-mN979kKyFBwKuc3I-DxDJ7TCHYlMsJURkV5FDNKwdcSvc7dUcMHdE4Xia8dKwe2iPKx8AQzi2Do4jsv9g191wo2uCQBjBX5pKFNWSm-mjzofx2qrgfHFIp_D5_cpJb4RhKpyx5w0ZRb3MXLpsICGM-570OivKaq75fmkMpHL26_hzzUgAek0YAaSR2ThCZBTJcMFErbdnKwATD3oAOgPNJA3dtvM0pw7cYk0JoFCTz54kj6_7c5j5ZleTb0d4JQlXzLJjhJyUPn8SseyFjww2rZzby_t9pU9euDjvCPzg1DmHVxki9ZEnjoWVCBievnrF7lSFUoRvlcYkmUvghzWSdjfaRZhzJhOLnbep2i0nL7DbwY0Za3mrXUVHLINBqxnjMBTxcjLq-VDzEx-STc3ShNaHS7F_5-kU6b675cNtYPQ3Kr21qKLWMswPH44rw0SI7qaC4tFCj_VE3WPRwxeOxAFL8__argMN8JeFrsEwevQoseeVZB39bK8ddvLlp1xxqDw2TF9eFRrbi5zY0ecxjla9j0vrm4ScweBdJge1XJSmDgZek6UjAzf1rYOl75c5zUwDAM1uxpDff_4TjwR6Y9m8L0gSZSq1gDw4YWhBr7xBXdl94

{
  "product_name": "Red Shirt Ultra",
  "product_description": "Uniqlo top flag branch, high quality",
  "product_price": 1202,
  "product_quantity": null,
  "product_type": "Clothing",
  "product_attributes": {
    "brand": "Jacky 1012",
    "size": "ML"
  }
}

### CREATE DISCOUNT
POST {{url_dev}}/discount
content-type: application/json
x-api-key: secrectapikey
x-client-id: 64ca8bd32c151b425bad9932
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGNhOGJkMzJjMTUxYjQyNWJhZDk5MzIiLCJlbWFpbCI6InZkaGxvbmcxMjAyQGdtYWlsLmNvbSIsImlhdCI6MTY5NDk1ODc4MSwiZXhwIjoxNjk1MTMxNTgxfQ.IO0EHLPrQJ5aZVLLDDgzj5rqcnrn6ZjkHJyiPC1j2td9my4lnFSTDZ6GZcqhuqgSIIp4JNUvaV8fHjn1kwEMhFHO_uWBjAlWit7H2ms2xb6BVLOxH06SZxR4UAzOP6Ab_8Bt90ISbiw4kH3JNaWtbvJknT2vF-xJoKpgHH77Kn_eBdVmQXat82BYifum5FdkAHUprQqRPjo0_CN9NW1gngY52Zk_F2scpWoA8bGdpWqecY9-bgY4R7Lz-G5s9DZ5vUBknWeuEAJ0mZwROi4nXC7dpt1bzEsoN0KkORn4doWuMbgRxHel2aMq3FPim01WhldO9ivUlHoLQ_6lwnJazqEDbjjBXfR8RzQXxK5fW1kUSDJyclSz5zIgzcGbnR5nxMvVkCfhL4JVCeZXYlXhCEa_JHoRP6z0AaGQztxo_D8PFP2r96nMoPxBUh_Omk7HH3x8xzW8ERhYANlW96ALOvINvenikpnXp-xRFQIacUlkPGhkn-83kDKtIB-Fduxf47e78gbuXsMYTMSWInqDInLr0426vGu-AJ8fmJAdV4Gn-9oHBEw78C94y6aZfrrrG7LS30NeAECNS62ra2jPhi4nNUoT1ss3_Ggpzarl_bFnv2zE6jmvhvrnQpex7WdpVsd5HjSnmlVB8eaDI1MbvRrwku17j4BKWCW_B3AIWsw
x-rtoken-id: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGNhOGJkMzJjMTUxYjQyNWJhZDk5MzIiLCJlbWFpbCI6InZkaGxvbmcxMjAyQGdtYWlsLmNvbSIsImlhdCI6MTY5NDk1ODc4MSwiZXhwIjoxNjk1NTYzNTgxfQ.SVARJo2kAXPhgAO85eincoOFjSua-Dni7xHL48zuh2jpP6x_1U7uZll3GYqS4D2blG85-O7HgRHTECe-vaBalKISlVbGJFb1-LUwXWkFmIop0NoSAsLiR9pva0sIEcG4wBSLx13IGrk1l7jx6wvRuMTPX1bJWVF571u0VqLvAEfmxEdl1cRdfzFizQm_Qtkt_7OGCYyaydPQejINtaIK2q9_V3ig9sq64gz8B-BarPZf2sj0YKGV9eSLci5QJUGjgYYFykHe3qYtOFFvGnMDOt5HMxNvLrq3c1bB6Uj2Wg2g9f32yK7OpZKk26ZA1CelBtMQfkoqaB8pOJQbNb7E5I_28zD4OPCnv4UHjyMQEyMo6uI6P-wbL6KI7pL8PXf0jVdLQNOwlWVBwVn5n5Ay_chV53eRsqGt2BJbycQNYJrAmLqCMblk8cjTsl2siDEQCIh2q_RqDU9aJ7Qee3AESwMqabElKMH6WOH1H4vOacAGc6LPpZitQLxVLt6kroJbiA3bIgwDvb06-UP8Yrjnb01pYn0WuVstAXfQcCCP5CuXHtSZ4eG-Vhb1Jazs4UpQBE4tmT7c7PcNb7_3M7-FBp2uV3c4DPGYPIAlS7a340j3aNLaYA8AcnMacG3EjQ1xQHaX7pq-_7gb57aF2pQKK6ALFn95ge5u3g4VwRepRmM

{
    "discount_name": "Mostover Discord",
    "discount_description": "Discount dop dop dis dis",
    "discount_value": 3,
    "discount_code": "ACCEL-1202",
    "discount_start_date": "2023-09-17 08:44:00",
    "discount_end_date": "2023-10-17 08:00:00",
    "discount_max_uses": 100,
    "discount_users_count": 0,
    "discount_users_used": [],
    "discount_max_uses_per_uses": 1,
    "discount_min_order_value": 20000,
    "discount_is_active": true,
    "discount_type": "percentage",
    "discount_apply_to": "specific",
    "discount_products": ["64ff3eccd02f39200627c861", "65008b4e09994bef47972dc8"]
}

### GET LIST PRODUCT USED DISCOUNT 
GET {{url_dev}}/discount/list-product-code?discount_code=ACCEL-1202&discount_shop=64ca8bd32c151b425bad9932
content-type: application/json

### GET LIST DISCOUNT BY SHOP
GET {{url_dev}}/discount?discount_shop=64ca8bd32c151b425bad9932
content-type: application/json
x-api-key: secrectapikey
x-client-id: 64ca8bd32c151b425bad9932
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGNhOGJkMzJjMTUxYjQyNWJhZDk5MzIiLCJlbWFpbCI6InZkaGxvbmcxMjAyQGdtYWlsLmNvbSIsImlhdCI6MTY5NDk1ODc4MSwiZXhwIjoxNjk1MTMxNTgxfQ.IO0EHLPrQJ5aZVLLDDgzj5rqcnrn6ZjkHJyiPC1j2td9my4lnFSTDZ6GZcqhuqgSIIp4JNUvaV8fHjn1kwEMhFHO_uWBjAlWit7H2ms2xb6BVLOxH06SZxR4UAzOP6Ab_8Bt90ISbiw4kH3JNaWtbvJknT2vF-xJoKpgHH77Kn_eBdVmQXat82BYifum5FdkAHUprQqRPjo0_CN9NW1gngY52Zk_F2scpWoA8bGdpWqecY9-bgY4R7Lz-G5s9DZ5vUBknWeuEAJ0mZwROi4nXC7dpt1bzEsoN0KkORn4doWuMbgRxHel2aMq3FPim01WhldO9ivUlHoLQ_6lwnJazqEDbjjBXfR8RzQXxK5fW1kUSDJyclSz5zIgzcGbnR5nxMvVkCfhL4JVCeZXYlXhCEa_JHoRP6z0AaGQztxo_D8PFP2r96nMoPxBUh_Omk7HH3x8xzW8ERhYANlW96ALOvINvenikpnXp-xRFQIacUlkPGhkn-83kDKtIB-Fduxf47e78gbuXsMYTMSWInqDInLr0426vGu-AJ8fmJAdV4Gn-9oHBEw78C94y6aZfrrrG7LS30NeAECNS62ra2jPhi4nNUoT1ss3_Ggpzarl_bFnv2zE6jmvhvrnQpex7WdpVsd5HjSnmlVB8eaDI1MbvRrwku17j4BKWCW_B3AIWsw
x-rtoken-id: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGNhOGJkMzJjMTUxYjQyNWJhZDk5MzIiLCJlbWFpbCI6InZkaGxvbmcxMjAyQGdtYWlsLmNvbSIsImlhdCI6MTY5NDk1ODc4MSwiZXhwIjoxNjk1NTYzNTgxfQ.SVARJo2kAXPhgAO85eincoOFjSua-Dni7xHL48zuh2jpP6x_1U7uZll3GYqS4D2blG85-O7HgRHTECe-vaBalKISlVbGJFb1-LUwXWkFmIop0NoSAsLiR9pva0sIEcG4wBSLx13IGrk1l7jx6wvRuMTPX1bJWVF571u0VqLvAEfmxEdl1cRdfzFizQm_Qtkt_7OGCYyaydPQejINtaIK2q9_V3ig9sq64gz8B-BarPZf2sj0YKGV9eSLci5QJUGjgYYFykHe3qYtOFFvGnMDOt5HMxNvLrq3c1bB6Uj2Wg2g9f32yK7OpZKk26ZA1CelBtMQfkoqaB8pOJQbNb7E5I_28zD4OPCnv4UHjyMQEyMo6uI6P-wbL6KI7pL8PXf0jVdLQNOwlWVBwVn5n5Ay_chV53eRsqGt2BJbycQNYJrAmLqCMblk8cjTsl2siDEQCIh2q_RqDU9aJ7Qee3AESwMqabElKMH6WOH1H4vOacAGc6LPpZitQLxVLt6kroJbiA3bIgwDvb06-UP8Yrjnb01pYn0WuVstAXfQcCCP5CuXHtSZ4eG-Vhb1Jazs4UpQBE4tmT7c7PcNb7_3M7-FBp2uV3c4DPGYPIAlS7a340j3aNLaYA8AcnMacG3EjQ1xQHaX7pq-_7gb57aF2pQKK6ALFn95ge5u3g4VwRepRmM

### GET DISCOUNT AMOUNT
POST {{url_dev}}/discount/amount
content-type: application/json
x-api-key: secrectapikey
x-client-id: 64ca8bd32c151b425bad9932
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGNhOGJkMzJjMTUxYjQyNWJhZDk5MzIiLCJlbWFpbCI6InZkaGxvbmcxMjAyQGdtYWlsLmNvbSIsImlhdCI6MTY5NDk1ODc4MSwiZXhwIjoxNjk1MTMxNTgxfQ.IO0EHLPrQJ5aZVLLDDgzj5rqcnrn6ZjkHJyiPC1j2td9my4lnFSTDZ6GZcqhuqgSIIp4JNUvaV8fHjn1kwEMhFHO_uWBjAlWit7H2ms2xb6BVLOxH06SZxR4UAzOP6Ab_8Bt90ISbiw4kH3JNaWtbvJknT2vF-xJoKpgHH77Kn_eBdVmQXat82BYifum5FdkAHUprQqRPjo0_CN9NW1gngY52Zk_F2scpWoA8bGdpWqecY9-bgY4R7Lz-G5s9DZ5vUBknWeuEAJ0mZwROi4nXC7dpt1bzEsoN0KkORn4doWuMbgRxHel2aMq3FPim01WhldO9ivUlHoLQ_6lwnJazqEDbjjBXfR8RzQXxK5fW1kUSDJyclSz5zIgzcGbnR5nxMvVkCfhL4JVCeZXYlXhCEa_JHoRP6z0AaGQztxo_D8PFP2r96nMoPxBUh_Omk7HH3x8xzW8ERhYANlW96ALOvINvenikpnXp-xRFQIacUlkPGhkn-83kDKtIB-Fduxf47e78gbuXsMYTMSWInqDInLr0426vGu-AJ8fmJAdV4Gn-9oHBEw78C94y6aZfrrrG7LS30NeAECNS62ra2jPhi4nNUoT1ss3_Ggpzarl_bFnv2zE6jmvhvrnQpex7WdpVsd5HjSnmlVB8eaDI1MbvRrwku17j4BKWCW_B3AIWsw
x-rtoken-id: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGNhOGJkMzJjMTUxYjQyNWJhZDk5MzIiLCJlbWFpbCI6InZkaGxvbmcxMjAyQGdtYWlsLmNvbSIsImlhdCI6MTY5NDk1ODc4MSwiZXhwIjoxNjk1NTYzNTgxfQ.SVARJo2kAXPhgAO85eincoOFjSua-Dni7xHL48zuh2jpP6x_1U7uZll3GYqS4D2blG85-O7HgRHTECe-vaBalKISlVbGJFb1-LUwXWkFmIop0NoSAsLiR9pva0sIEcG4wBSLx13IGrk1l7jx6wvRuMTPX1bJWVF571u0VqLvAEfmxEdl1cRdfzFizQm_Qtkt_7OGCYyaydPQejINtaIK2q9_V3ig9sq64gz8B-BarPZf2sj0YKGV9eSLci5QJUGjgYYFykHe3qYtOFFvGnMDOt5HMxNvLrq3c1bB6Uj2Wg2g9f32yK7OpZKk26ZA1CelBtMQfkoqaB8pOJQbNb7E5I_28zD4OPCnv4UHjyMQEyMo6uI6P-wbL6KI7pL8PXf0jVdLQNOwlWVBwVn5n5Ay_chV53eRsqGt2BJbycQNYJrAmLqCMblk8cjTsl2siDEQCIh2q_RqDU9aJ7Qee3AESwMqabElKMH6WOH1H4vOacAGc6LPpZitQLxVLt6kroJbiA3bIgwDvb06-UP8Yrjnb01pYn0WuVstAXfQcCCP5CuXHtSZ4eG-Vhb1Jazs4UpQBE4tmT7c7PcNb7_3M7-FBp2uV3c4DPGYPIAlS7a340j3aNLaYA8AcnMacG3EjQ1xQHaX7pq-_7gb57aF2pQKK6ALFn95ge5u3g4VwRepRmM

{
    "discount_code": "ACCEL-1202",
    "discount_shop": "64ca8bd32c151b425bad9932",
    "user_id": "1",
    "products": [
        {
            "_id": "64ff3eccd02f39200627c861",
            "quantity": 5,
            "price": 1202
        },
        {
            "_id": "65008b4e09994bef47972dc8",
            "quantity": 3,
            "price": 100
        }
    ]
}

### GET USER CART LIST
GET {{url_dev}}/cart
content-type: application/json
x-api-key: secrectapikey
x-client-id: 64ca8bd32c151b425bad9932
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGNhOGJkMzJjMTUxYjQyNWJhZDk5MzIiLCJlbWFpbCI6InZkaGxvbmcxMjAyQGdtYWlsLmNvbSIsImlhdCI6MTY5ODY2OTE2MCwiZXhwIjoxNjk4ODQxOTYwfQ.Q5xFvksFNBO_LW2aPGtU1W_2OKO2K_PGOslrsKJN7Vh25uWDr0qgQIM-mglD39Wc7AL-cX8lgK29_Lrvs4YtnN5EJjfKzYUOJJkb19Qwxw6cnnt6ANl5tacSEVPvZeSC8MNYvFk-vTCCF1NhJHx_X4d-o-KvVQCTL8cC0J5VRRf0qdYcQoSzsRztn-CwumXMqMiHRcxKs8oPTaqsBe7vUdZmINwGTxX2crtUPaxtIN38AIka7EtTBgvq2wXhWUZZ4TNsqh1g40lr3eSphtw8IajTo2RKYmdHp69i8WNc_m4cERwoL8kTdtPHSIG2k0ty6B27elU82F2wrVlgHQs7xGI-DEwGR0GaU9m8MSnjjXRTGnfk5txjdxaHBWw2J2eEtqVXV19ItUB66cUfg-vg7cZ7ct8WbHcEw8HnciSqBDI__TUZmfS337-FWGrvTWBaH-jYzPHLP4LjX3JmS7tJ6TPzYsFJZkdPauhE7HsdfFyTy6kThQWhL0vBVGTC0J6HdQqdcaFDxY8Yrc80dgrWJysmZ4uv395IwC7kiRG-TxtU1QM7za-milQiNkJlgfPQ_bX687xMl9X5Yy9VBfVEvJYAIK8kxxY5ejO_W9tO6vzLmp8i9ewr489qkxITT5JsD1RXOXIcFRxsoDdqrQ821ooiKTo0DhEF0u9tsGgKjsI
x-rtoken-id: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGNhOGJkMzJjMTUxYjQyNWJhZDk5MzIiLCJlbWFpbCI6InZkaGxvbmcxMjAyQGdtYWlsLmNvbSIsImlhdCI6MTY5ODY2OTE2MCwiZXhwIjoxNjk5MjczOTYwfQ.0nPpBculqTS88jIHvNyisg37BI2isKBYx2_3sfFyOq6lQEmJmHSqNMFKRpZL3I69Z6BX-UHEvxcT2g4QIoP-K5tNH2_ryU6YdE_zWlMURHmnr-eTOTHgz95ztuVD-fGKRAzSySTQ5IjxHVmMob1Df6tnGHr31sPeeYOQvfMNXS9NSzDtRqxAB-oxSw1IafCATZs_HY-UerLdI4lcvRd3NTKZsyzf9s99bNpQJ9hS6NoZRbejyXaxgGijv4lRHncnecNaaDSZFOwxQSU1m2bVoKRnWPFuNAGbLkEir_87NxySFtZ31KAacUDq4bMP8TBhv8zpq_z7n9C7xfhgtC466pYYLQM49VX0eIgKPY_RCDQYkEAG_oRl7rCebTldcGouVTYIVtwvFmqgkns_VzYOaFw6S3mWMeLo8FoTxFNV8nyWXlIkOVQwJtyxb2vZFxW2qAS6hBXijTTmjnxlfmpDqKhJmwMKR46dVqItF9Z__wVkW83han0siZtpFS4qanq6wswHtRYIjxHJKWrkJLauXgvhWRrYGq-RfuucGYkJCBDdiBL_-FOHFNMImMbS-03wRC-iThWyeLYFB9RZPSlsOHks4u8wU-wikqCXNLQjMIkVev_M9oByT0cMUE_kl01smf44xWa_Ljh0YJ8g_0Pb1mEOOmubAaxbIyRmLKMsKAQ


### ADD PRODUCT USER CART 
POST {{url_dev}}/cart
content-type: application/json
x-api-key: secrectapikey
x-client-id: 64ca8bd32c151b425bad9932
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGNhOGJkMzJjMTUxYjQyNWJhZDk5MzIiLCJlbWFpbCI6InZkaGxvbmcxMjAyQGdtYWlsLmNvbSIsImlhdCI6MTY5ODY2OTE2MCwiZXhwIjoxNjk4ODQxOTYwfQ.Q5xFvksFNBO_LW2aPGtU1W_2OKO2K_PGOslrsKJN7Vh25uWDr0qgQIM-mglD39Wc7AL-cX8lgK29_Lrvs4YtnN5EJjfKzYUOJJkb19Qwxw6cnnt6ANl5tacSEVPvZeSC8MNYvFk-vTCCF1NhJHx_X4d-o-KvVQCTL8cC0J5VRRf0qdYcQoSzsRztn-CwumXMqMiHRcxKs8oPTaqsBe7vUdZmINwGTxX2crtUPaxtIN38AIka7EtTBgvq2wXhWUZZ4TNsqh1g40lr3eSphtw8IajTo2RKYmdHp69i8WNc_m4cERwoL8kTdtPHSIG2k0ty6B27elU82F2wrVlgHQs7xGI-DEwGR0GaU9m8MSnjjXRTGnfk5txjdxaHBWw2J2eEtqVXV19ItUB66cUfg-vg7cZ7ct8WbHcEw8HnciSqBDI__TUZmfS337-FWGrvTWBaH-jYzPHLP4LjX3JmS7tJ6TPzYsFJZkdPauhE7HsdfFyTy6kThQWhL0vBVGTC0J6HdQqdcaFDxY8Yrc80dgrWJysmZ4uv395IwC7kiRG-TxtU1QM7za-milQiNkJlgfPQ_bX687xMl9X5Yy9VBfVEvJYAIK8kxxY5ejO_W9tO6vzLmp8i9ewr489qkxITT5JsD1RXOXIcFRxsoDdqrQ821ooiKTo0DhEF0u9tsGgKjsI
x-rtoken-id: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGNhOGJkMzJjMTUxYjQyNWJhZDk5MzIiLCJlbWFpbCI6InZkaGxvbmcxMjAyQGdtYWlsLmNvbSIsImlhdCI6MTY5ODY2OTE2MCwiZXhwIjoxNjk5MjczOTYwfQ.0nPpBculqTS88jIHvNyisg37BI2isKBYx2_3sfFyOq6lQEmJmHSqNMFKRpZL3I69Z6BX-UHEvxcT2g4QIoP-K5tNH2_ryU6YdE_zWlMURHmnr-eTOTHgz95ztuVD-fGKRAzSySTQ5IjxHVmMob1Df6tnGHr31sPeeYOQvfMNXS9NSzDtRqxAB-oxSw1IafCATZs_HY-UerLdI4lcvRd3NTKZsyzf9s99bNpQJ9hS6NoZRbejyXaxgGijv4lRHncnecNaaDSZFOwxQSU1m2bVoKRnWPFuNAGbLkEir_87NxySFtZ31KAacUDq4bMP8TBhv8zpq_z7n9C7xfhgtC466pYYLQM49VX0eIgKPY_RCDQYkEAG_oRl7rCebTldcGouVTYIVtwvFmqgkns_VzYOaFw6S3mWMeLo8FoTxFNV8nyWXlIkOVQwJtyxb2vZFxW2qAS6hBXijTTmjnxlfmpDqKhJmwMKR46dVqItF9Z__wVkW83han0siZtpFS4qanq6wswHtRYIjxHJKWrkJLauXgvhWRrYGq-RfuucGYkJCBDdiBL_-FOHFNMImMbS-03wRC-iThWyeLYFB9RZPSlsOHks4u8wU-wikqCXNLQjMIkVev_M9oByT0cMUE_kl01smf44xWa_Ljh0YJ8g_0Pb1mEOOmubAaxbIyRmLKMsKAQ

{
    "product": {
      "productId": "64ff3eccd02f39200627c861",
      "shopId": "64ca8bd32c151b425bad9932",
      "quantity": 1,
      "price": 1202
    }
}

### DELETE PRODUCT USER CART 
DELETE {{url_dev}}/cart/64ff3eccd02f39200627c861
content-type: application/json
x-api-key: secrectapikey
x-client-id: 64ca8bd32c151b425bad9932
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGNhOGJkMzJjMTUxYjQyNWJhZDk5MzIiLCJlbWFpbCI6InZkaGxvbmcxMjAyQGdtYWlsLmNvbSIsImlhdCI6MTY5ODY2OTE2MCwiZXhwIjoxNjk4ODQxOTYwfQ.Q5xFvksFNBO_LW2aPGtU1W_2OKO2K_PGOslrsKJN7Vh25uWDr0qgQIM-mglD39Wc7AL-cX8lgK29_Lrvs4YtnN5EJjfKzYUOJJkb19Qwxw6cnnt6ANl5tacSEVPvZeSC8MNYvFk-vTCCF1NhJHx_X4d-o-KvVQCTL8cC0J5VRRf0qdYcQoSzsRztn-CwumXMqMiHRcxKs8oPTaqsBe7vUdZmINwGTxX2crtUPaxtIN38AIka7EtTBgvq2wXhWUZZ4TNsqh1g40lr3eSphtw8IajTo2RKYmdHp69i8WNc_m4cERwoL8kTdtPHSIG2k0ty6B27elU82F2wrVlgHQs7xGI-DEwGR0GaU9m8MSnjjXRTGnfk5txjdxaHBWw2J2eEtqVXV19ItUB66cUfg-vg7cZ7ct8WbHcEw8HnciSqBDI__TUZmfS337-FWGrvTWBaH-jYzPHLP4LjX3JmS7tJ6TPzYsFJZkdPauhE7HsdfFyTy6kThQWhL0vBVGTC0J6HdQqdcaFDxY8Yrc80dgrWJysmZ4uv395IwC7kiRG-TxtU1QM7za-milQiNkJlgfPQ_bX687xMl9X5Yy9VBfVEvJYAIK8kxxY5ejO_W9tO6vzLmp8i9ewr489qkxITT5JsD1RXOXIcFRxsoDdqrQ821ooiKTo0DhEF0u9tsGgKjsI
x-rtoken-id: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGNhOGJkMzJjMTUxYjQyNWJhZDk5MzIiLCJlbWFpbCI6InZkaGxvbmcxMjAyQGdtYWlsLmNvbSIsImlhdCI6MTY5ODY2OTE2MCwiZXhwIjoxNjk5MjczOTYwfQ.0nPpBculqTS88jIHvNyisg37BI2isKBYx2_3sfFyOq6lQEmJmHSqNMFKRpZL3I69Z6BX-UHEvxcT2g4QIoP-K5tNH2_ryU6YdE_zWlMURHmnr-eTOTHgz95ztuVD-fGKRAzSySTQ5IjxHVmMob1Df6tnGHr31sPeeYOQvfMNXS9NSzDtRqxAB-oxSw1IafCATZs_HY-UerLdI4lcvRd3NTKZsyzf9s99bNpQJ9hS6NoZRbejyXaxgGijv4lRHncnecNaaDSZFOwxQSU1m2bVoKRnWPFuNAGbLkEir_87NxySFtZ31KAacUDq4bMP8TBhv8zpq_z7n9C7xfhgtC466pYYLQM49VX0eIgKPY_RCDQYkEAG_oRl7rCebTldcGouVTYIVtwvFmqgkns_VzYOaFw6S3mWMeLo8FoTxFNV8nyWXlIkOVQwJtyxb2vZFxW2qAS6hBXijTTmjnxlfmpDqKhJmwMKR46dVqItF9Z__wVkW83han0siZtpFS4qanq6wswHtRYIjxHJKWrkJLauXgvhWRrYGq-RfuucGYkJCBDdiBL_-FOHFNMImMbS-03wRC-iThWyeLYFB9RZPSlsOHks4u8wU-wikqCXNLQjMIkVev_M9oByT0cMUE_kl01smf44xWa_Ljh0YJ8g_0Pb1mEOOmubAaxbIyRmLKMsKAQ

### CHECKOUT REVIEW USER
POST {{url_dev}}/checkout/review
content-type: application/json
x-api-key: secrectapikey
x-client-id: 64ca8bd32c151b425bad9932
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGNhOGJkMzJjMTUxYjQyNWJhZDk5MzIiLCJlbWFpbCI6InZkaGxvbmcxMjAyQGdtYWlsLmNvbSIsImlhdCI6MTcwMzYwMzg0NSwiZXhwIjoxNzA2MTk1ODQ1fQ.c1sgb4sBQWd-4TLMtj8WjR_UZKTmBelNPq0MwJaLkLaDxTY5EsG1uVvhRDSvc6Sr1uoT5heefsJPXJV6tK8h8xOIsabDz3mvfkd1l8hl3u41bTL8mhji7BzFa5gouac08hpmAzHJbhut0JtKLGJMny0bvnCDA5d_4_MnBcb-Qk4rmBF3noIOiJkYD6SNYTCWpi4jPBkITLNLqVvs96NbJOzVNPLzgJ1xY8C_ijT0WdSLHkQMGtLCeZhaiKHn6KU2w86ktDbUESr2pgMxBiyuL8RbvMX2i3o5pK0S3u0pAoycxI4zHkHF0TR30AmXnxxKbBqo7wd4pz2MNjtorA9I3he-OPE4mn0CmS675PPeqrRyBrxZdV-x0UJULVbj6AuJPyZO1ednOgfuYDDAkE1EIyrDtGOdIQBIbjEGRSjCX1EHAhn7PFS5HZarYNl8314dK7eSEirzcnr1n0YzMNTON_P4PPss7_nNkleWjhgZWrhpnYfGxAT8PcfKFI5AWQIalbo3mc8jKe73LO-0RLmX_40BZn5uTS3mT80_4suXGjMdgB0uW4V0Ys2WOjbfetvhlB5eAFMhy9Z6fs4ZiYztPmUjGGzlPS8LiHABzVxqteTYwqghzsRUZOdobaEv4_-3EWc5UHhKek3X13mioEKPa5SDMtFUmIj4ejjf4hREqb4
x-rtoken-id: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGNhOGJkMzJjMTUxYjQyNWJhZDk5MzIiLCJlbWFpbCI6InZkaGxvbmcxMjAyQGdtYWlsLmNvbSIsImlhdCI6MTcwMzYwMzg0NSwiZXhwIjoxNzA2MTk1ODQ1fQ.c1sgb4sBQWd-4TLMtj8WjR_UZKTmBelNPq0MwJaLkLaDxTY5EsG1uVvhRDSvc6Sr1uoT5heefsJPXJV6tK8h8xOIsabDz3mvfkd1l8hl3u41bTL8mhji7BzFa5gouac08hpmAzHJbhut0JtKLGJMny0bvnCDA5d_4_MnBcb-Qk4rmBF3noIOiJkYD6SNYTCWpi4jPBkITLNLqVvs96NbJOzVNPLzgJ1xY8C_ijT0WdSLHkQMGtLCeZhaiKHn6KU2w86ktDbUESr2pgMxBiyuL8RbvMX2i3o5pK0S3u0pAoycxI4zHkHF0TR30AmXnxxKbBqo7wd4pz2MNjtorA9I3he-OPE4mn0CmS675PPeqrRyBrxZdV-x0UJULVbj6AuJPyZO1ednOgfuYDDAkE1EIyrDtGOdIQBIbjEGRSjCX1EHAhn7PFS5HZarYNl8314dK7eSEirzcnr1n0YzMNTON_P4PPss7_nNkleWjhgZWrhpnYfGxAT8PcfKFI5AWQIalbo3mc8jKe73LO-0RLmX_40BZn5uTS3mT80_4suXGjMdgB0uW4V0Ys2WOjbfetvhlB5eAFMhy9Z6fs4ZiYztPmUjGGzlPS8LiHABzVxqteTYwqghzsRUZOdobaEv4_-3EWc5UHhKek3X13mioEKPa5SDMtFUmIj4ejjf4hREqb4

{
  "cartId": "653fe8aa10f21100f25b34ca",
  "shop_order": [
    {
      "shopId": "64ca8bd32c151b425bad9932",
      "shop_discounts": [
        {
          "codeId": "ACCEL-1202",
          "discountId": "650707b0f8948fb2f4cdf1dc"
        }
      ], 
      "item_products": [
        {
          "productId": "64ff3eccd02f39200627c861",
          "quantity": 2,
          "price": 1202
        },
        {
          "productId": "65008b4e09994bef47972dc8",
          "quantity": 3,
          "price": 1202
        }
      ]
    },
    {
      "shopId": "65411d6abe7a79029ecadbd4",
      "shop_discounts": [], 
      "item_products": [
        {
          "productId": "65411ecf22126e08b4cd9f51",
          "quantity": 1,
          "price": 1202
        }
      ]
    }
  ]
}

### CREATE COMMENT
POST {{url_dev}}/comment
content-type: application/json
x-api-key: secrectapikey
x-client-id: 64ca8bd32c151b425bad9932
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGNhOGJkMzJjMTUxYjQyNWJhZDk5MzIiLCJlbWFpbCI6InZkaGxvbmcxMjAyQGdtYWlsLmNvbSIsImlhdCI6MTcwMzYwMzg0NSwiZXhwIjoxNzA2MTk1ODQ1fQ.c1sgb4sBQWd-4TLMtj8WjR_UZKTmBelNPq0MwJaLkLaDxTY5EsG1uVvhRDSvc6Sr1uoT5heefsJPXJV6tK8h8xOIsabDz3mvfkd1l8hl3u41bTL8mhji7BzFa5gouac08hpmAzHJbhut0JtKLGJMny0bvnCDA5d_4_MnBcb-Qk4rmBF3noIOiJkYD6SNYTCWpi4jPBkITLNLqVvs96NbJOzVNPLzgJ1xY8C_ijT0WdSLHkQMGtLCeZhaiKHn6KU2w86ktDbUESr2pgMxBiyuL8RbvMX2i3o5pK0S3u0pAoycxI4zHkHF0TR30AmXnxxKbBqo7wd4pz2MNjtorA9I3he-OPE4mn0CmS675PPeqrRyBrxZdV-x0UJULVbj6AuJPyZO1ednOgfuYDDAkE1EIyrDtGOdIQBIbjEGRSjCX1EHAhn7PFS5HZarYNl8314dK7eSEirzcnr1n0YzMNTON_P4PPss7_nNkleWjhgZWrhpnYfGxAT8PcfKFI5AWQIalbo3mc8jKe73LO-0RLmX_40BZn5uTS3mT80_4suXGjMdgB0uW4V0Ys2WOjbfetvhlB5eAFMhy9Z6fs4ZiYztPmUjGGzlPS8LiHABzVxqteTYwqghzsRUZOdobaEv4_-3EWc5UHhKek3X13mioEKPa5SDMtFUmIj4ejjf4hREqb4
x-rtoken-id: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGNhOGJkMzJjMTUxYjQyNWJhZDk5MzIiLCJlbWFpbCI6InZkaGxvbmcxMjAyQGdtYWlsLmNvbSIsImlhdCI6MTcwMzYwMzg0NSwiZXhwIjoxNzA2MTk1ODQ1fQ.c1sgb4sBQWd-4TLMtj8WjR_UZKTmBelNPq0MwJaLkLaDxTY5EsG1uVvhRDSvc6Sr1uoT5heefsJPXJV6tK8h8xOIsabDz3mvfkd1l8hl3u41bTL8mhji7BzFa5gouac08hpmAzHJbhut0JtKLGJMny0bvnCDA5d_4_MnBcb-Qk4rmBF3noIOiJkYD6SNYTCWpi4jPBkITLNLqVvs96NbJOzVNPLzgJ1xY8C_ijT0WdSLHkQMGtLCeZhaiKHn6KU2w86ktDbUESr2pgMxBiyuL8RbvMX2i3o5pK0S3u0pAoycxI4zHkHF0TR30AmXnxxKbBqo7wd4pz2MNjtorA9I3he-OPE4mn0CmS675PPeqrRyBrxZdV-x0UJULVbj6AuJPyZO1ednOgfuYDDAkE1EIyrDtGOdIQBIbjEGRSjCX1EHAhn7PFS5HZarYNl8314dK7eSEirzcnr1n0YzMNTON_P4PPss7_nNkleWjhgZWrhpnYfGxAT8PcfKFI5AWQIalbo3mc8jKe73LO-0RLmX_40BZn5uTS3mT80_4suXGjMdgB0uW4V0Ys2WOjbfetvhlB5eAFMhy9Z6fs4ZiYztPmUjGGzlPS8LiHABzVxqteTYwqghzsRUZOdobaEv4_-3EWc5UHhKek3X13mioEKPa5SDMtFUmIj4ejjf4hREqb4

{
  "productId": "64ff3eccd02f39200627c861",
  "parentCommentId": "659419c753d07892cd685096",
  "content": "comment 1.2.1.2"
}

### GET COMMENT
GET {{url_dev}}/comment?productId=64ff3eccd02f39200627c861&parentCommentId=657d3253365a430c71fd9bc6
content-type: application/json
x-api-key: secrectapikey
x-client-id: 64ca8bd32c151b425bad9932
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGNhOGJkMzJjMTUxYjQyNWJhZDk5MzIiLCJlbWFpbCI6InZkaGxvbmcxMjAyQGdtYWlsLmNvbSIsImlhdCI6MTcwMzYwMzg0NSwiZXhwIjoxNzA2MTk1ODQ1fQ.c1sgb4sBQWd-4TLMtj8WjR_UZKTmBelNPq0MwJaLkLaDxTY5EsG1uVvhRDSvc6Sr1uoT5heefsJPXJV6tK8h8xOIsabDz3mvfkd1l8hl3u41bTL8mhji7BzFa5gouac08hpmAzHJbhut0JtKLGJMny0bvnCDA5d_4_MnBcb-Qk4rmBF3noIOiJkYD6SNYTCWpi4jPBkITLNLqVvs96NbJOzVNPLzgJ1xY8C_ijT0WdSLHkQMGtLCeZhaiKHn6KU2w86ktDbUESr2pgMxBiyuL8RbvMX2i3o5pK0S3u0pAoycxI4zHkHF0TR30AmXnxxKbBqo7wd4pz2MNjtorA9I3he-OPE4mn0CmS675PPeqrRyBrxZdV-x0UJULVbj6AuJPyZO1ednOgfuYDDAkE1EIyrDtGOdIQBIbjEGRSjCX1EHAhn7PFS5HZarYNl8314dK7eSEirzcnr1n0YzMNTON_P4PPss7_nNkleWjhgZWrhpnYfGxAT8PcfKFI5AWQIalbo3mc8jKe73LO-0RLmX_40BZn5uTS3mT80_4suXGjMdgB0uW4V0Ys2WOjbfetvhlB5eAFMhy9Z6fs4ZiYztPmUjGGzlPS8LiHABzVxqteTYwqghzsRUZOdobaEv4_-3EWc5UHhKek3X13mioEKPa5SDMtFUmIj4ejjf4hREqb4
x-rtoken-id: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGNhOGJkMzJjMTUxYjQyNWJhZDk5MzIiLCJlbWFpbCI6InZkaGxvbmcxMjAyQGdtYWlsLmNvbSIsImlhdCI6MTcwMzYwMzg0NSwiZXhwIjoxNzA2MTk1ODQ1fQ.c1sgb4sBQWd-4TLMtj8WjR_UZKTmBelNPq0MwJaLkLaDxTY5EsG1uVvhRDSvc6Sr1uoT5heefsJPXJV6tK8h8xOIsabDz3mvfkd1l8hl3u41bTL8mhji7BzFa5gouac08hpmAzHJbhut0JtKLGJMny0bvnCDA5d_4_MnBcb-Qk4rmBF3noIOiJkYD6SNYTCWpi4jPBkITLNLqVvs96NbJOzVNPLzgJ1xY8C_ijT0WdSLHkQMGtLCeZhaiKHn6KU2w86ktDbUESr2pgMxBiyuL8RbvMX2i3o5pK0S3u0pAoycxI4zHkHF0TR30AmXnxxKbBqo7wd4pz2MNjtorA9I3he-OPE4mn0CmS675PPeqrRyBrxZdV-x0UJULVbj6AuJPyZO1ednOgfuYDDAkE1EIyrDtGOdIQBIbjEGRSjCX1EHAhn7PFS5HZarYNl8314dK7eSEirzcnr1n0YzMNTON_P4PPss7_nNkleWjhgZWrhpnYfGxAT8PcfKFI5AWQIalbo3mc8jKe73LO-0RLmX_40BZn5uTS3mT80_4suXGjMdgB0uW4V0Ys2WOjbfetvhlB5eAFMhy9Z6fs4ZiYztPmUjGGzlPS8LiHABzVxqteTYwqghzsRUZOdobaEv4_-3EWc5UHhKek3X13mioEKPa5SDMtFUmIj4ejjf4hREqb4

### DELETE COMMENT
DELETE  {{url_dev}}/comment?productId=64ff3eccd02f39200627c861&commentId=6594196f53d07892cd68507a
x-api-key: secrectapikey
x-client-id: 64ca8bd32c151b425bad9932
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGNhOGJkMzJjMTUxYjQyNWJhZDk5MzIiLCJlbWFpbCI6InZkaGxvbmcxMjAyQGdtYWlsLmNvbSIsImlhdCI6MTcwMzYwMzg0NSwiZXhwIjoxNzA2MTk1ODQ1fQ.c1sgb4sBQWd-4TLMtj8WjR_UZKTmBelNPq0MwJaLkLaDxTY5EsG1uVvhRDSvc6Sr1uoT5heefsJPXJV6tK8h8xOIsabDz3mvfkd1l8hl3u41bTL8mhji7BzFa5gouac08hpmAzHJbhut0JtKLGJMny0bvnCDA5d_4_MnBcb-Qk4rmBF3noIOiJkYD6SNYTCWpi4jPBkITLNLqVvs96NbJOzVNPLzgJ1xY8C_ijT0WdSLHkQMGtLCeZhaiKHn6KU2w86ktDbUESr2pgMxBiyuL8RbvMX2i3o5pK0S3u0pAoycxI4zHkHF0TR30AmXnxxKbBqo7wd4pz2MNjtorA9I3he-OPE4mn0CmS675PPeqrRyBrxZdV-x0UJULVbj6AuJPyZO1ednOgfuYDDAkE1EIyrDtGOdIQBIbjEGRSjCX1EHAhn7PFS5HZarYNl8314dK7eSEirzcnr1n0YzMNTON_P4PPss7_nNkleWjhgZWrhpnYfGxAT8PcfKFI5AWQIalbo3mc8jKe73LO-0RLmX_40BZn5uTS3mT80_4suXGjMdgB0uW4V0Ys2WOjbfetvhlB5eAFMhy9Z6fs4ZiYztPmUjGGzlPS8LiHABzVxqteTYwqghzsRUZOdobaEv4_-3EWc5UHhKek3X13mioEKPa5SDMtFUmIj4ejjf4hREqb4
x-rtoken-id: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGNhOGJkMzJjMTUxYjQyNWJhZDk5MzIiLCJlbWFpbCI6InZkaGxvbmcxMjAyQGdtYWlsLmNvbSIsImlhdCI6MTcwMzYwMzg0NSwiZXhwIjoxNzA2MTk1ODQ1fQ.c1sgb4sBQWd-4TLMtj8WjR_UZKTmBelNPq0MwJaLkLaDxTY5EsG1uVvhRDSvc6Sr1uoT5heefsJPXJV6tK8h8xOIsabDz3mvfkd1l8hl3u41bTL8mhji7BzFa5gouac08hpmAzHJbhut0JtKLGJMny0bvnCDA5d_4_MnBcb-Qk4rmBF3noIOiJkYD6SNYTCWpi4jPBkITLNLqVvs96NbJOzVNPLzgJ1xY8C_ijT0WdSLHkQMGtLCeZhaiKHn6KU2w86ktDbUESr2pgMxBiyuL8RbvMX2i3o5pK0S3u0pAoycxI4zHkHF0TR30AmXnxxKbBqo7wd4pz2MNjtorA9I3he-OPE4mn0CmS675PPeqrRyBrxZdV-x0UJULVbj6AuJPyZO1ednOgfuYDDAkE1EIyrDtGOdIQBIbjEGRSjCX1EHAhn7PFS5HZarYNl8314dK7eSEirzcnr1n0YzMNTON_P4PPss7_nNkleWjhgZWrhpnYfGxAT8PcfKFI5AWQIalbo3mc8jKe73LO-0RLmX_40BZn5uTS3mT80_4suXGjMdgB0uW4V0Ys2WOjbfetvhlB5eAFMhy9Z6fs4ZiYztPmUjGGzlPS8LiHABzVxqteTYwqghzsRUZOdobaEv4_-3EWc5UHhKek3X13mioEKPa5SDMtFUmIj4ejjf4hREqb4